language: smalltalk
sudo: false

install:
 - pip install --user benchupload

after_success:
 - python -mbenchupload --dir=$SMALLTALK_CI_BUILD

after_failure:
 - python -mbenchupload --dir=$SMALLTALK_CI_BUILD
 
os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0
  - Pharo-5.0
