"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestMathTNSE,
	#superclass : #PackageManifest,
	#category : 'Math-TSNE'
}

{ #category : #'meta-data' }
ManifestMathTNSE class >> description [ ^ 'Implementation of t-Distributed Stochastic Neighbor Embedding (t-SNE) algorithm

https://lvdmaaten.github.io/tsne/'
]
