SystemOrganization addCategory: #'Math-DHB-Numerical'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-Distribution'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-Eigenvalues'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-FunctionIterator'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-Interpolator'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-Matrix'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-Polynomials'!
SystemOrganization addCategory: 'Math-DHB-Numerical-Math-UtilsAccumulator'!
