versions
version069: spec
	<version: '0.69' imports: #('0.37-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'stable'.
		spec description: 'version 0.69'.
		spec author: 'SergeStinckwich'.
		spec timestamp: '2017-01-31T15:18:04.656268+01:00'.
		spec 
			project: 'SMark' with: '1.0.1';
			project: 'XMLWriter' with: '2.3.9'.
		spec 
			package: 'Math-Core' with: 'Math-Core-StephaneDucasse.12';
			package: 'Math-Core-Process' with: 'Math-Core-Process-MobiusEng.6';
			package: 'Math-Core-Distribution' with: 'Math-Core-Distribution-SergeStinckwich.11';
			package: 'Math-Chromosome' with: 'Math-Chromosome-StephaneDucasse.1';
			package: 'Math-UtilsDataServer' with: 'Math-UtilsDataServer-StephaneDucasse.1';
			package: 'Math-Series' with: 'Math-Series-MobiusEng.3';
			package: 'Math-DistributionGamma' with: 'Math-DistributionGamma-StephaneDucasse.3';
			package: 'Math-DistributionBeta' with: 'Math-DistributionBeta-StephaneDucasse.3';
			package: 'Math-DistributionForHistogram' with: 'Math-DistributionForHistogram-SergeStinckwich.4';
			package: 'Math-Random' with: 'Math-Random-StephaneDucasse.17';
			package: 'Math-KDTree' with: 'Math-KDTree-wernerkassens.34';
			package: 'Math-Complex' with: 'Math-Complex-wernerkassens.9';
			package: 'Math-Quaternion' with: 'Math-Quaternion-wernerkassens.10';
			package: 'Math-FastFourierTransform' with: 'Math-FastFourierTransform-StephaneDucasse.2';
			package: 'ExtendedNumberParser' with: 'ExtendedNumberParser-nice.1';
			package: 'Math-ArbitraryPrecisionFloat' with: 'Math-ArbitraryPrecisionFloat-SergeStinckwich.1';
			package: 'Math-Quantile' with: 'Math-Quantile-SergeStinckwich.6';
			package: 'Math-Tests-Quantile' with: 'Math-Tests-Quantile-SergeStinckwich.4';
			package: 'Math-Tests-Random' with: 'Math-Tests-Random-StephaneDucasse.14';
			package: 'Math-Tests-KDTree' with: 'Math-Tests-KDTree-StephaneDucasse.27';
			package: 'Math-Tests-Quaternion' with: 'Math-Tests-Quaternion-SergeStinckwich.6';
			package: 'Math-Tests-ArbitraryPrecisionFloat' with: 'Math-Tests-ArbitraryPrecisionFloat-SergeStinckwich.1';
			package: 'Math-Accuracy-Core' with: 'Math-Accuracy-Core-StephaneDucasse.3';
			package: 'Math-Tests-Accuracy' with: 'Math-Tests-Accuracy-StephaneDucasse.3';
			package: 'Math-Benchmarks-KDTree' with: 'Math-Benchmarks-KDTree-StephaneDucasse.9';
			package: 'Math-Number-Extensions' with: 'Math-Number-Extensions.Pharo-DanielUber.8';
			package: 'Math-StatisticalMoments' with: 'Math-StatisticalMoments-WernerKassens.5';
			package: 'Math-DHB-Numerical' with: 'Math-DHB-Numerical-SergeStinckwich.73';
			package: 'Math-FunctionFit' with: 'Math-FunctionFit-SergeStinckwich.5';
			package: 'Math-Tests-FastFourierTransform' with: 'Math-Tests-FastFourierTransform-StephaneDucasse.2';
			package: 'Math-Tests-DHB-Numerical' with: 'Math-Tests-DHB-Numerical-SergeStinckwich.33';
			package: 'Math-KolmogorovSmirnov' with: 'Math-KolmogorovSmirnov-WernerKassens.1';
			package: 'Math-Tests-KolmogorovSmirnov' with: 'Math-Tests-KolmogorovSmirnov-StephaneDucasse.2';
			package: 'Math-KernelSmoothing' with: 'Math-KernelSmoothing-WernerKassens.2';
			package: 'Math-AutomaticDifferenciation' with: 'Math-AutomaticDifferenciation-StephaneDucasse.2';
			package: 'Math-Tests-AutomaticDifferenciation' with: 'Math-Tests-AutomaticDifferenciation-StephaneDucasse.3';
			package: 'Math-QuaternionExtensions' with: 'Math-QuaternionExtensions-SergeStinckwich.4';
			package: 'Math-DHB-NumericalExtensions' with: 'Math-DHB-NumericalExtensions-StephaneDucasse.8';
			package: 'Math-ODE' with: 'Math-ODE-StephaneDucasse.32';
			package: 'Math-Benchmarks-ODE' with: 'Math-Benchmarks-ODE-YuriyTymchuk.7';
			package: 'Math-Accuracy-ODE' with: 'Math-Accuracy-ODE-StephaneDucasse.6';
			package: 'Math-Tests-ODE' with: 'Math-Tests-ODE-StephaneDucasse.17';
			package: 'Math-ComplexExtensions' with: 'Math-ComplexExtensions-SergeStinckwich.6';
			package: 'Math-Tests-Complex' with: 'Math-Tests-Complex-SergeStinckwich.7';
			package: 'Math-PrincipalComponentAnalysis' with: 'Math-PrincipalComponentAnalysis-StephaneDucasse.2';
			package: 'Math-RandomDistributionBased' with: 'Math-RandomDistributionBased-StephaneDucasse.2';
			package: 'Math-Clustering' with: 'Math-Clustering-MobiusEng.3';
			package: 'Math-Tests-Clustering' with: 'Math-Tests-Clustering-StephaneDucasse.5';
			package: 'Math-Test-Matrix' with: 'Math-Test-Matrix-SergeStinckwich.2';
			package: 'Math-Matrix' with: 'Math-Matrix-MobiusEng.2';
			package: 'Math-DHB-wk' with: 'Math-DHB-wk-MobiusEng.11';
			package: 'Math-Tests-FunctionFit' with: 'Math-Tests-FunctionFit-SergeStinckwich.7';
			package: 'Math-Tests-DHB-wk' with: 'Math-Tests-DHB-wk-StephaneDucasse.9'. ].
